import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as XLSX from 'xlsx';
import * as FileSystem from 'expo-file-system/legacy';
import { Assessment, Evaluation } from '../services/storage';

export const exportGradeCardToPDF = async (evaluation: Evaluation, assessment: Assessment) => {
    const scorePercentage = (evaluation.obtainedMarks / evaluation.totalMarks) * 100;

    const html = `
        <html>
            <head>
                <style>
                    body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
                    .header { text-align: center; border-bottom: 2px solid #3498db; padding-bottom: 20px; }
                    .title { font-size: 28px; color: #3498db; margin: 0; }
                    .subtitle { font-size: 16px; color: #7f8c8d; }
                    .details { margin: 30px 0; display: flex; flex-wrap: wrap; }
                    .detail-item { width: 50%; margin-bottom: 15px; }
                    .label { font-weight: bold; color: #2c3e50; }
                    .score-box { background: #f8f9fa; padding: 20px; border-radius: 10px; text-align: center; margin-bottom: 30px; }
                    .score-value { font-size: 36px; font-weight: bold; color: #27ae60; }
                    .breakdown { width: 100%; border-collapse: collapse; }
                    .breakdown th { background: #3498db; color: white; padding: 12px; text-align: left; }
                    .breakdown td { padding: 12px; border-bottom: 1px solid #eee; }
                    .feedback { font-style: italic; color: #7f8c8d; margin-top: 5px; }
                </style>
            </head>
            <body>
                <div class="header">
                    <h1 class="title">GRADE CARD</h1>
                    <p class="subtitle">Generated by CheckerQ AI</p>
                </div>
                
                <div class="details">
                    <div class="detail-item"><span class="label">Assessment:</span> ${assessment.title}</div>
                    <div class="detail-item"><span class="label">Subject:</span> ${assessment.subject}</div>
                    <div class="detail-item"><span class="label">Teacher:</span> ${assessment.teacherName}</div>
                    <div class="detail-item"><span class="label">Class:</span> ${assessment.classRoom}</div>
                    <div class="detail-item"><span class="label">Date:</span> ${new Date(evaluation.createdAt).toLocaleDateString()}</div>
                </div>

                <div class="score-box">
                    <div class="score-value">${evaluation.obtainedMarks} / ${evaluation.totalMarks}</div>
                    <div class="label">Final Score (${scorePercentage.toFixed(1)}%)</div>
                </div>

                <h3>Question Breakdown</h3>
                <table class="breakdown">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Question & Feedback</th>
                            <th>Marks</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${evaluation.results.map((res, i) => {
        const q = assessment.questions.find(fq => fq.id === res.questionId);
        return `
                                <tr>
                                    <td>${i + 1}</td>
                                    <td>
                                        <div><strong>Q:</strong> ${q?.text || 'N/A'}</div>
                                        <div><strong>Ans:</strong> ${res.studentAnswer}</div>
                                        <div class="feedback"><strong>Feedback:</strong> ${res.feedback}</div>
                                    </td>
                                    <td>${res.obtainedMarks}</td>
                                </tr>
                            `;
    }).join('')}
                    </tbody>
                </table>

                <div style="margin-top: 40px;">
                    <h3>Overall Feedback</h3>
                    <p>${evaluation.overallFeedback}</p>
                </div>
            </body>
        </html>
    `;

    try {
        const { uri } = await Print.printToFileAsync({ html });
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
        console.error('PDF Export Error:', error);
        throw error;
    }
};

export const exportAllAssessmentsToExcel = async (assessments: Assessment[], evaluations: Evaluation[]) => {
    // 1. Group evaluations by Class
    const evaluationsByClass: Record<string, any[]> = {};

    evaluations.forEach(ev => {
        const assessment = assessments.find(a => a.id === ev.assessmentId);
        const className = assessment?.classRoom || 'Unassigned';

        if (!evaluationsByClass[className]) {
            evaluationsByClass[className] = [];
        }

        evaluationsByClass[className].push({
            'Student Name': ev.studentName || 'Unknown',
            'Assessment Title': assessment?.title || 'N/A',
            'Subject': assessment?.subject || 'N/A',
            'Obtained Marks': ev.obtainedMarks,
            'Total Marks': ev.totalMarks,
            'Percentage': ((ev.obtainedMarks / ev.totalMarks) * 100).toFixed(2) + '%',
            'Feedback': ev.overallFeedback,
            'Date': new Date(ev.createdAt).toLocaleString()
        });
    });

    const wb = XLSX.utils.book_new();

    // 2. Create a sheet for each class
    Object.keys(evaluationsByClass).forEach(className => {
        const ws = XLSX.utils.json_to_sheet(evaluationsByClass[className]);

        // Sanitize sheet name (Excel limits: max 31 chars, no brackets, etc.)
        const sheetName = className.replace(/[\[\]\*\?\/\\\:]/g, '').substring(0, 31);

        XLSX.utils.book_append_sheet(wb, ws, sheetName || 'Sheet1');
    });

    const wbout = XLSX.write(wb, { type: 'base64', bookType: 'xlsx' });
    const uri = FileSystem.cacheDirectory + 'CheckerQ_Report_MultiSheet.xlsx';

    try {
        await FileSystem.writeAsStringAsync(uri, wbout, { encoding: FileSystem.EncodingType.Base64 });
        await Sharing.shareAsync(uri, {
            mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            dialogTitle: 'Share Assessment Report',
            UTI: 'com.microsoft.excel.xlsx'
        });
    } catch (error) {
        console.error('Excel Export Error:', error);
        throw error;
    }
};
