import * as Sharing from 'expo-sharing';
import { Assessment, Evaluation } from '../services/storage';

export const shareEvaluation = async (evaluation: Evaluation, assessment: Assessment) => {
    try {
        const shareText = `
📊 Evaluation Report

Student: ${evaluation.studentName || 'N/A'}
Subject: ${assessment.subject}
Class: ${assessment.classRoom}

Score: ${evaluation.obtainedMarks}/${evaluation.totalMarks} (${Math.round((evaluation.obtainedMarks / evaluation.totalMarks) * 100)}%)

Overall Feedback:
${evaluation.overallFeedback || 'No feedback provided'}

---
Generated by CheckerQ
    `.trim();

        if (await Sharing.isAvailableAsync()) {
            await Sharing.shareAsync('data:text/plain;base64,' + btoa(shareText), {
                mimeType: 'text/plain',
                dialogTitle: 'Share Evaluation',
            });
        }
    } catch (error) {
        console.error('Share evaluation error:', error);
        throw new Error('Failed to share evaluation');
    }
};

export const shareClassReport = async (classRoom: string, evaluations: Evaluation[], assessments: Assessment[]) => {
    try {
        const classEvals = evaluations.filter(e => {
            const assessment = assessments.find(a => a.id === e.assessmentId);
            return assessment?.classRoom === classRoom;
        });

        const avgScore = classEvals.reduce((sum, e) => sum + (e.obtainedMarks / e.totalMarks) * 100, 0) / classEvals.length;
        const passRate = (classEvals.filter(e => (e.obtainedMarks / e.totalMarks) * 100 >= 60).length / classEvals.length) * 100;

        const shareText = `
📊 Class Report - ${classRoom}

Total Students: ${classEvals.length}
Average Score: ${Math.round(avgScore)}%
Pass Rate: ${Math.round(passRate)}%

---
Generated by CheckerQ
    `.trim();

        if (await Sharing.isAvailableAsync()) {
            await Sharing.shareAsync('data:text/plain;base64,' + btoa(shareText), {
                mimeType: 'text/plain',
                dialogTitle: 'Share Class Report',
            });
        }
    } catch (error) {
        console.error('Share class report error:', error);
        throw new Error('Failed to share class report');
    }
};
